In [1]:
import numpy as np

In [2]:
#we can take a list and convert it to a numpy array
my_nums = [2, 5, 6, 12]

In [3]:
nums = np.array(my_nums)

In [4]:
nums

array([ 2,  5,  6, 12])

In [5]:
type(nums)

numpy.ndarray

In [6]:
type(nums[0])

numpy.int32

In [7]:
nums.dtype

dtype('int32')

In [8]:
my_nums2 = [2, 5, 6, 12, 'a']

In [9]:
second = np.array(my_nums2)

In [10]:
second

array(['2', '5', '6', '12', 'a'], dtype='<U11')

In [11]:
type(second)

numpy.ndarray

In [13]:
second.dtype

dtype('<U11')

In [14]:
nums

array([ 2,  5,  6, 12])

In [15]:
#mean, median, max, min, sum 

In [16]:
x2 = np.random.randint(10, size = (3, 4))

In [17]:
x2

array([[9, 0, 5, 4],
       [6, 0, 7, 0],
       [3, 9, 2, 4]])

In [18]:
#sum the columns of x2
x2.sum()

49

In [19]:
x2.sum(axis = 0)

array([18,  9, 14,  8])

In [20]:
x2.sum(axis = 1)

array([18, 13, 18])

In [21]:
x2.transpose()

array([[9, 6, 3],
       [0, 0, 9],
       [5, 7, 2],
       [4, 0, 4]])

In [23]:
x2.transpose().sum(axis = 1).min()

8

In [24]:
nums

array([ 2,  5,  6, 12])

In [40]:
nums < 4

array([ True, False, False, False])

In [42]:
nums[(nums > 4) & (nums < 6)]

array([5])

In [43]:
nums[(nums < 4) | (nums > 6)]

array([ 2, 12])

In [26]:
nums[nums < 4]

array([2])

In [30]:
#fancy indexing
nums[[1,3]]

array([ 5, 12])

In [31]:
nums[[True, True, True, False]]

array([2, 5, 6])

In [32]:
ind = [0,3]
nums[ind]

array([ 2, 12])

In [33]:
nums

array([ 2,  5,  6, 12])

In [35]:
np.any(nums < 100)

True

In [37]:
np.all (nums < 12)

False

In [39]:
np.count_nonzero(nums)

4

In [45]:
x2 = np.random.randint(10, size = 10)

In [46]:
x2

array([1, 5, 5, 4, 2, 5, 2, 5, 4, 1])

In [49]:
sorted_x2 = np.sort(x2)

In [50]:
x2

array([1, 5, 5, 4, 2, 5, 2, 5, 4, 1])

In [51]:
sorted_x2 

array([1, 1, 2, 2, 4, 4, 5, 5, 5, 5])

In [52]:
sorted_x2[0] = -88

In [53]:
sorted_x2

array([-88,   1,   2,   2,   4,   4,   5,   5,   5,   5])

In [54]:
x2

array([1, 5, 5, 4, 2, 5, 2, 5, 4, 1])

In [55]:
x2.sort()

In [56]:
x2

array([1, 1, 2, 2, 4, 4, 5, 5, 5, 5])

In [57]:
#argsort
x2 = np.random.randint(10, size = 10)

In [58]:
x2

array([9, 0, 2, 7, 2, 2, 9, 4, 1, 7])

In [60]:
indexes_for_sorting = np.argsort(x2)

In [63]:
print(indexes_for_sorting)

[1 8 2 4 5 7 3 9 0 6]


In [62]:
type(indexes_for_sorting)

numpy.ndarray