In [1]:
seq = ['a', 'b', 'e', 'y']

In [2]:
seq

['a', 'b', 'e', 'y']

In [6]:
#to print out all elements in the list seq
for item in seq:
    print(item)

a
b
e
y


In [7]:
courses = [('CSC245', 4), ('CSC115', 3)]

In [11]:
for a, b in courses:
    print (a + ' has the following credits ' + str(b))

CSC245 has the following credits 4
CSC115 has the following credits 3


numpy has a type:  ndarray which stored data efficiently

In [12]:
import numpy as np

In [13]:
# this will give me documentation
np?

In [14]:
np.random.seed(0)

In [16]:
# if I don't want to use np.random each time
from numpy import random

In [17]:
#shift tab will give documentation
x1 = random.randint(10, size= 6)

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
type(x1)

numpy.ndarray

In [20]:
x1.ndim

1

In [21]:
x1.shape

(6,)

In [22]:
x1.size

6

In [24]:
len(x1)

6

In [26]:
x2 = random.randint(10, size = (3, 4))

In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [34]:
#x2[0][1]
x2[0,1]

5

In [37]:
x2[1]

array([7, 6, 8, 8])

In [28]:
type(x2)

numpy.ndarray

In [29]:
x2.size

12

In [30]:
len(x2)

3

In [31]:
x2.ndim

2

In [32]:
x2.dtype

dtype('int32')

In [38]:
#slicing 
x1

array([5, 0, 3, 3, 7, 9])

In [39]:
x1[1:]

array([0, 3, 3, 7, 9])

In [40]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [42]:
x2[1:,2:]

array([[8, 8],
       [7, 7]])

In [43]:
x3 = random.randint(10, size = (5, 7))

In [44]:
x3

array([[8, 1, 5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7, 0],
       [1, 9, 9, 0, 4, 7, 3],
       [2, 7, 2, 0, 0, 4, 5]])

In [46]:
#slicing as per example during class
#slicing gives a view not its own copy
slice_of_x3 = x3[1:3,2:5]

In [47]:
slice_of_x3

array([[3, 5, 0],
       [3, 3, 3]])

In [50]:
slice_of_x3[0,1] = -100

In [51]:
slice_of_x3

array([[   3, -100,    0],
       [   3,    3,    3]])

In [52]:
x3

array([[   8,    1,    5,    9,    8,    9,    4],
       [   3,    0,    3, -100,    0,    2,    3],
       [   8,    1,    3,    3,    3,    7,    0],
       [   1,    9,    9,    0,    4,    7,    3],
       [   2,    7,    2,    0,    0,    4,    5]])

In [53]:
piece_of_x3 = x3[1:3,2:5].copy()

In [54]:
piece_of_x3

array([[   3, -100,    0],
       [   3,    3,    3]])

In [ ]:
#create a one dimensional numpy array with 15 elements
#using randint  with randintegers taken from from 5 to 25 
#(including 25)

In [55]:
x5 = random.randint(5,26,size = 15)

In [56]:
x5

array([10, 11, 13, 25, 22, 20,  9, 14, 15,  6,  6, 12, 14,  8, 11])

In [57]:
zeros = np.zeros(16)

In [58]:
ones = np.ones(5)

In [59]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
ones

array([1., 1., 1., 1., 1.])

In [61]:
ones.dtype

dtype('float64')

In [62]:
nums = np.arange(40,50)

In [66]:
nums.dtype

dtype('int32')

In [67]:
x1.dtype

dtype('int32')

In [70]:
np.concatenate((nums, x1))

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49,  5,  0,  3,  3,  7,  9])

In [93]:
 x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [94]:
x6 = random.randint(10,size = (2,4))

In [95]:
x6

array([[7, 5, 9, 0],
       [2, 7, 2, 9]])

In [97]:
np.concatenate((x2, x6))

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7],
       [7, 5, 9, 0],
       [2, 7, 2, 9]])

In [101]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [99]:
x6 = random.randint(10,size = (3,8))


In [100]:
x6

array([[8, 2, 3, 2, 0, 8, 8, 3],
       [8, 2, 8, 4, 3, 0, 4, 3],
       [6, 9, 8, 0, 8, 5, 9, 0]])

In [103]:
np.concatenate((x2, x6), axis = 1)

array([[3, 5, 2, 4, 8, 2, 3, 2, 0, 8, 8, 3],
       [7, 6, 8, 8, 8, 2, 8, 4, 3, 0, 4, 3],
       [1, 6, 7, 7, 6, 9, 8, 0, 8, 5, 9, 0]])

In [104]:
x1

array([5, 0, 3, 3, 7, 9])

In [105]:
#universal functions

In [107]:
x1** 2

array([25,  0,  9,  9, 49, 81], dtype=int32)

In [108]:
#summary statistics
x1.sum()

27

In [109]:
x1.mean()

4.5

In [110]:
x1.min()

0

In [111]:
x1.max()

9

In [112]:
np.max(x1)

9

In [113]:
np.median(x1)

4.0

In [116]:
x1

array([5, 0, 3, 3, 7, 9])

In [117]:
x1.mean()

4.5

In [118]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [127]:
#axis is which dimension is collapsed
np.sum(x2, axis = 1)

array([14, 29, 21])

In [128]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [129]:
x6

array([[8, 2, 3, 2, 0, 8, 8, 3],
       [8, 2, 8, 4, 3, 0, 4, 3],
       [6, 9, 8, 0, 8, 5, 9, 0]])

In [133]:
#minimum in the middle row
type(x6[1])

numpy.ndarray

In [134]:
minnum = np.min(x6[1])

In [144]:
#largest row sum
np.max(np.sum(x6, axis = 1))

45

In [138]:
np.sum(x6, axis = 1)

array([34, 32, 45])

In [140]:
type(np.sum(x6))

numpy.int32

In [145]:
x1

array([5, 0, 3, 3, 7, 9])

In [146]:
x1 > 3

array([ True, False, False, False,  True,  True])

In [147]:
x1 % 2 == 1

array([ True, False,  True,  True,  True,  True])

In [148]:
x1[x1 % 2 == 1]

array([5, 3, 3, 7, 9])

In [149]:
x6

array([[8, 2, 3, 2, 0, 8, 8, 3],
       [8, 2, 8, 4, 3, 0, 4, 3],
       [6, 9, 8, 0, 8, 5, 9, 0]])

In [150]:
x1

array([5, 0, 3, 3, 7, 9])

In [152]:
len(x1[x1 % 3 == 0])

4