In [1]:
import numpy as np

In [2]:
# we can take a list and convert it to a numpy array
my_nums = [2, 5, 6, 12]

In [3]:
nums = np.array(my_nums)

In [4]:
nums

array([ 2,  5,  6, 12])

In [5]:
print(type(nums)) # n-dim array

<class 'numpy.ndarray'>


In [6]:
type(nums[0]) # checking type in individual list

numpy.int32

In [7]:
nums.dtype # checking type using dtype 

dtype('int32')

In [8]:
my_nums2 = [2, 5, 6, 12, 'a']

In [9]:
second = np.array(my_nums2)

In [10]:
second # all strings because there is an string and all are objects

array(['2', '5', '6', '12', 'a'], dtype='<U11')

In [11]:
type(second)

numpy.ndarray

In [12]:
second.dtype

dtype('<U11')

In [13]:
nums

array([ 2,  5,  6, 12])

In [14]:
# mean, median, min, max, sum

In [15]:
x2 = np.random.randint(10, size = (3,4))

In [16]:
x2

array([[6, 6, 9, 9],
       [6, 7, 4, 4],
       [4, 5, 5, 9]])

In [21]:
# sum the columns of x2: axis = 0 => columns
x2.sum(axis = 0)

array([16, 18, 18, 22])

In [22]:
# sum of rows of x2: axis = 1 => rows
x2.sum(axis = 1)

array([30, 21, 23])

In [23]:
x2.transpose() # switch rows and columns

array([[6, 6, 4],
       [6, 7, 5],
       [9, 4, 5],
       [9, 4, 9]])

In [24]:
x2.transpose().sum(axis = 1) # transpose x2 and the sum of rows of transposed x2

array([16, 18, 18, 22])

In [25]:
x2.transpose().sum(axis = 0) # transpose x2 and the sum of columns of transposed x2

array([30, 21, 23])

In [26]:
x2.transpose().sum(axis = 1).min() #transpose, sum and getting the min of the sum 

16

In [27]:
nums

array([ 2,  5,  6, 12])

In [38]:
nums < 4

array([ True, False, False, False])

In [40]:
nums[(nums < 4) & (nums < 6)] # conditional statements and

array([2])

In [41]:
nums[(nums < 4) | (nums > 6)] # conditional statements or

array([ 2, 12])

In [29]:
nums[nums < 4] # only returns the true value

array([2])

In [30]:
nums[[1,2]] # returns which elements of the numpy array

array([5, 6])

In [32]:
ind = [0,3]
nums[ind] # subset the indexs in ind for nums. Basically pulling out the indexs for nums

array([ 2, 12])

In [34]:
np.any(nums > 100) # find any (at least one) that is greater than 100

False

In [35]:
np.any(nums < 100) # find any (at least one) that is less than 100

True

In [36]:
np.all(nums < 12) # find if ALL (everything in list) that is less than 12

False

In [37]:
np.count_nonzero(nums)

4

In [42]:
x2 = np.random.randint(10, size = 10)

In [43]:
x2

array([4, 2, 2, 9, 7, 5, 0, 5, 8, 6])

In [66]:
x2.sort() # sort an array in place, changing the array
x2

array([0, 2, 2, 4, 5, 5, 6, 7, 8, 9])

In [49]:
x2[::-1].sort()
x2

array([9, 8, 7, 6, 5, 5, 4, 2, 2, 0])

In [60]:
sorted_x2 = np.sort(x2) # sorted x2, using np.sort() does not change the array, returns a copy of a sorted array

In [65]:
sorted_x2 # a new array, not a view

array([-88,   2,   2,   4,   5,   5,   6,   7,   8,   9])

In [67]:
#argsort
np.argsort(x2) # returns the indexs of the array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [74]:
x3 = np.random.randint(20, size = 10)
x3

array([12, 15,  3,  9,  4, 18,  2, 19,  4,  5])

In [73]:
np.argsort(x3)

array([6, 0, 5, 4, 9, 7, 1, 2, 3, 8], dtype=int64)

In [75]:
indexes_for_sorting = np.argsort(x3) # saving the indexs of x3

In [76]:
indexes_for_sorting

array([6, 2, 4, 8, 9, 3, 0, 1, 5, 7], dtype=int64)