In [1]:
seq = ['a', 'b', 'e', 'y']

In [2]:
seq

['a', 'b', 'e', 'y']

In [3]:
# to print out all elements in the list seq
for item in seq:
    print(item)

a
b
e
y


In [4]:
courses = [('CSC245',4),("CSC115",3)] # [(a,b),(a,b)]

In [5]:
for a, b in courses: # unpacking tuple
    print(a + ' has the following credits ' + str(b))

CSC245 has the following credits 4
CSC115 has the following credits 3


Advantage of NumPy has a type: ndarray (n-dimensional array) which stored data efficiently

In [6]:
import numpy as np

In [7]:
# This will give me documentation
np?

In [8]:
np.random.seed(0)

In [9]:
# If I don't want to use np.random each time. Then import the below
from numpy import random

In [10]:
# random.randint(low, high=none, size=, datatype=) // random numbers of int
# press shift + tab will give documentation
x1 = random.randint(10, size=6)

In [11]:
# n dimension
x1.ndim

1

In [12]:
x1.shape

(6,)

In [13]:
x1.size

6

In [14]:
len(x1)

6

In [15]:
type(x1)

numpy.ndarray

In [16]:
# 2d array
x2 = random.randint(10, size=(3,4))

In [17]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
# x2[0][1]
x2[0,1]

5

In [19]:
type(x2[1])

numpy.ndarray

In [20]:
type(x2)

numpy.ndarray

In [21]:
x2.size

12

In [22]:
len(x2)

3

In [23]:
x2.ndim

2

In [24]:
# .dtype : data type
x2.dtype

dtype('int32')

In [25]:
# slicing
x1

array([5, 0, 3, 3, 7, 9])

In [26]:
x1[1:]

array([0, 3, 3, 7, 9])

In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [28]:
x2[1:,2:]

array([[8, 8],
       [7, 7]])

In [29]:
x3 = random.randint(10, size=(5,7))

In [30]:
x3

array([[8, 1, 5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7, 0],
       [1, 9, 9, 0, 4, 7, 3],
       [2, 7, 2, 0, 0, 4, 5]])

In [31]:
# slicing as per example during class
# slicing gives a view, not its own copy
slice_of_x3 = x3[1:3,2:5]

In [32]:
slice_of_x3

array([[3, 5, 0],
       [3, 3, 3]])

In [33]:
slice_of_x3[0,1] = -100

In [34]:
slice_of_x3

array([[   3, -100,    0],
       [   3,    3,    3]])

In [35]:
x3

array([[   8,    1,    5,    9,    8,    9,    4],
       [   3,    0,    3, -100,    0,    2,    3],
       [   8,    1,    3,    3,    3,    7,    0],
       [   1,    9,    9,    0,    4,    7,    3],
       [   2,    7,    2,    0,    0,    4,    5]])

In [36]:
piece_of_x3 = x3[1:3,2:5].copy()

In [37]:
piece_of_x3

array([[   3, -100,    0],
       [   3,    3,    3]])

In [38]:
piece_of_x3[0,2] = -20

In [39]:
piece_of_x3

array([[   3, -100,  -20],
       [   3,    3,    3]])

In [40]:
# create a 1-D numpy array with 15 elements
#using randint range from 5 to 25 (including 25)
x5 = random.randint(5,26, size=15)
x5

array([10, 11, 13, 25, 22, 20,  9, 14, 15,  6,  6, 12, 14,  8, 11])

In [41]:
zeros = np.zeros(16)

In [42]:
ones = np.ones(5)

In [43]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
ones

array([1., 1., 1., 1., 1.])

In [45]:
ones.dtype

dtype('float64')

In [46]:
nums = np.arange(40,50)

In [47]:
nums

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [48]:
x1

array([5, 0, 3, 3, 7, 9])

In [49]:
np.concatenate((nums, x1))

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49,  5,  0,  3,  3,  7,  9])

In [50]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [56]:
x6 = random.randint(10, size=(2,4))

In [58]:
x6

array([[5, 9, 4, 4],
       [6, 4, 4, 3]])

In [60]:
np.concatenate((x2,x6), axis=0)

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7],
       [5, 9, 4, 4],
       [6, 4, 4, 3]])

In [62]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [63]:
x6 = random.randint(10,size=(3,8))

In [64]:
x6

array([[4, 4, 8, 4, 3, 7, 5, 5],
       [0, 1, 5, 9, 3, 0, 5, 0],
       [1, 2, 4, 2, 0, 3, 2, 0]])

In [67]:
np.concatenate((x2,x6), axis=1)

array([[3, 5, 2, 4, 4, 4, 8, 4, 3, 7, 5, 5],
       [7, 6, 8, 8, 0, 1, 5, 9, 3, 0, 5, 0],
       [1, 6, 7, 7, 1, 2, 4, 2, 0, 3, 2, 0]])

In [68]:
x1

array([5, 0, 3, 3, 7, 9])

In [69]:
# universal functions

In [71]:
x1 ** 2

array([25,  0,  9,  9, 49, 81], dtype=int32)

In [72]:
#summary statistics
# sum all elements in x1 array
x1.sum() 

27

In [73]:
# average of x1
x1.mean()

4.5

In [74]:
# smallest element in x1
x1.min()

0

In [75]:
# largest element in x1
x1.max()

9

In [79]:
np.median(x1)

4.0

In [80]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [81]:
x2.mean()

5.333333333333333

In [82]:
x2.sum()

64

In [84]:
# axis is which dimension is collapsed
np.sum(x2, axis=0) # sum each columns 

array([11, 17, 17, 19])

In [85]:
np.sum(x2, axis=1) # sum each rows

array([14, 29, 21])

In [86]:
x6

array([[4, 4, 8, 4, 3, 7, 5, 5],
       [0, 1, 5, 9, 3, 0, 5, 0],
       [1, 2, 4, 2, 0, 3, 2, 0]])

In [88]:
np.min(x6[1])

0

In [89]:
np.max(x6[2])

4

In [90]:
type(x6[1])

numpy.ndarray

In [93]:
# Find the largest row sum
np.max(np.sum(x6, axis = 1))

40

In [94]:
type(np.sum(x6))

numpy.int32

In [95]:
x1

array([5, 0, 3, 3, 7, 9])

In [96]:
x1 > 3

array([ True, False, False, False,  True,  True])

In [97]:
x1 % 2 == 1 # which are odd

array([ True, False,  True,  True,  True,  True])

In [98]:
x1[x1 % 2 == 1] # Gives back the elements are odd

array([5, 3, 3, 7, 9])

In [99]:
x6

array([[4, 4, 8, 4, 3, 7, 5, 5],
       [0, 1, 5, 9, 3, 0, 5, 0],
       [1, 2, 4, 2, 0, 3, 2, 0]])

In [102]:
x1[x1 % 3 == 0] # find which one can be divide by 3

array([0, 3, 3, 9])

In [103]:
len(x1[x1 % 3 == 0])

4